import ballerina/ai;
import ballerina/http;
import ballerina/time;
import ballerina/uuid;
import ballerinax/ai.openai;
import ballerinax/amp as _;

// Provide the OpenAI API key via Config.toml (configurable).
configurable string openAiApiKey = ?;

// Platform posts session_id/message (open record: tolerates the extra
// context field). ai:ChatReqMessage uses sessionId/message and ai:Listener
// locks you into that shape, so this uses http:Listener instead.
type ChatRequest record {
    string session_id;
    string message;
};

// Same mismatch on the way out: ai:ChatRespMessage uses "message", the
// platform expects "response". Closed record is fine here since outgoing
// values are not validated the way incoming ones are.
type ChatResponse record {|
    string response;
|};

// Root-mounted: exposes exactly POST /chat on port 8000, per the Chat Agent contract.
service / on new http:Listener(8000) {
    resource function post chat(@http:Payload ChatRequest request)
                        returns ChatResponse|error {
        string reply = check leaveAssistantAgent.run(request.message, request.session_id);
        return {response: reply};
    }
}

type LeaveType "annual"|"sick"|"unpaid";
type LeaveStatus "pending"|"approved"|"rejected"|"cancelled";

# One employee's leave balances.
#
# + name - The employee's display name
# + annualLeaveBalance - Remaining annual leave days
# + sickLeaveBalance - Remaining sick leave days
type Employee record {|
    string name;
    int annualLeaveBalance;
    int sickLeaveBalance;
|};

# A single leave request.
#
# + id - Unique identifier, generated by requestLeave
# + employeeId - Who this request belongs to
# + leaveType - annual, sick, or unpaid
# + startDate - First day of the leave
# + numberOfDays - How many days requested
# + reason - The employee's stated reason
# + status - pending, approved, rejected, or cancelled
# + managerNote - A note left by whoever approved or rejected the request, if any
# + createdAt - When the request was filed
type LeaveRequest record {|
    string id;
    string employeeId;
    LeaveType leaveType;
    time:Date startDate;
    int numberOfDays;
    string reason;
    LeaveStatus status = "pending";
    string? managerNote = ();
    time:Date createdAt;
|};

// Longer requests need manager approval regardless of balance.
const int AUTO_APPROVE_MAX_DAYS = 3;

isolated map<Employee> employees = {
    "E-3001": {name: "Priya Fernando", annualLeaveBalance: 14, sickLeaveBalance: 7},
    "E-3002": {name: "Kasun Silva", annualLeaveBalance: 3, sickLeaveBalance: 7}
};

isolated map<LeaveRequest> leaveRequests = {};

# Looks up an employee's remaining leave balances.
#
# + employeeId - The employee to look up
# + return - The employee's balances, or an error if no employee has that id
@ai:AgentTool
isolated function getLeaveBalance(string employeeId) returns Employee|error {
    lock {
        Employee? employee = employees[employeeId];
        if employee is () {
            return error(string `No employee found with id "${employeeId}"`);
        }
        return employee.clone();
    }
}

# Submits a new leave request. Annual and sick leave auto-approve if the
# balance allows; longer annual leave and unpaid leave wait for approval.
#
# + employeeId - Who is requesting leave
# + leaveType - annual, sick, or unpaid
# + startDate - The first day of the leave
# + numberOfDays - How many days, including the start date
# + reason - Why the employee is requesting this leave
# + return - The created request, or an error if the employee is unknown or the balance is insufficient
@ai:AgentTool
isolated function requestLeave(string employeeId, LeaveType leaveType, time:Date startDate,
        int numberOfDays, string reason) returns LeaveRequest|error {
    string id = uuid:createRandomUuid();
    LeaveStatus status = "pending";

    // Unpaid leave has no balance to check; it always waits for manager approval.
    lock {
        Employee? employee = employees[employeeId];
        if employee is () {
            return error(string `No employee found with id "${employeeId}"`);
        }

        if leaveType == "annual" {
            if numberOfDays > employee.annualLeaveBalance {
                return error(string `${employee.name} only has ${employee.annualLeaveBalance} day(s) of annual leave left, cannot request ${numberOfDays}`);
            }
            Employee updatedEmployee = employee.clone();
            updatedEmployee.annualLeaveBalance -= numberOfDays;
            employees[employeeId] = updatedEmployee;
            status = numberOfDays <= AUTO_APPROVE_MAX_DAYS ? "approved" : "pending";
        } else if leaveType == "sick" {
            if numberOfDays > employee.sickLeaveBalance {
                return error(string `${employee.name} only has ${employee.sickLeaveBalance} day(s) of sick leave left, cannot request ${numberOfDays}`);
            }
            Employee updatedEmployee = employee.clone();
            updatedEmployee.sickLeaveBalance -= numberOfDays;
            employees[employeeId] = updatedEmployee;
            status = "approved";
        }
    }

    LeaveRequest newRequest = {
        id,
        employeeId,
        leaveType,
        startDate,
        numberOfDays,
        reason,
        status,
        createdAt: time:utcToCivil(time:utcNow())
    };
    lock {
        leaveRequests[id] = newRequest.clone();
    }
    return newRequest;
}

# Lists every leave request filed by one employee, including past ones.
#
# + employeeId - The employee to list requests for
# + return - That employee's leave requests
@ai:AgentTool
isolated function listMyLeaveRequests(string employeeId) returns LeaveRequest[] {
    LeaveRequest[] allRequests;
    lock {
        allRequests = leaveRequests.toArray().clone();
    }
    return from LeaveRequest r in allRequests
        where r.employeeId == employeeId
        select r;
}

# Cancels a pending or approved leave request. Refunds any annual or
# sick leave balance that was deducted when the request was filed.
#
# + requestId - The request's id, as returned by requestLeave or listMyLeaveRequests
# + return - The updated request, or an error if no request has that id or it cannot be cancelled
@ai:AgentTool
isolated function cancelLeaveRequest(string requestId) returns LeaveRequest|error {
    LeaveRequest existing;
    lock {
        LeaveRequest? found = leaveRequests[requestId];
        if found is () {
            return error(string `No leave request found with id "${requestId}"`);
        }
        if found.status == "cancelled" || found.status == "rejected" {
            return error(string `Leave request "${requestId}" is already ${found.status} and cannot be cancelled again`);
        }
        existing = found.clone();
    }

    if existing.leaveType == "annual" || existing.leaveType == "sick" {
        lock {
            Employee? employee = employees[existing.employeeId];
            if employee is Employee {
                Employee refunded = employee.clone();
                if existing.leaveType == "annual" {
                    refunded.annualLeaveBalance += existing.numberOfDays;
                } else {
                    refunded.sickLeaveBalance += existing.numberOfDays;
                }
                employees[existing.employeeId] = refunded;
            }
        }
    }

    LeaveRequest updated = existing.clone();
    updated.status = "cancelled";
    lock {
        leaveRequests[requestId] = updated.clone();
    }
    return updated;
}

# Approves a pending leave request. Use rejectLeaveRequest to turn one down.
#
# + requestId - The request's id, as returned by requestLeave or listMyLeaveRequests
# + note - An optional note to attach, such as who approved it
# + return - The updated request, or an error if no request has that id or it is not pending
@ai:AgentTool
isolated function approveLeaveRequest(string requestId, string? note) returns LeaveRequest|error {
    lock {
        LeaveRequest? existing = leaveRequests[requestId];
        if existing is () {
            return error(string `No leave request found with id "${requestId}"`);
        }
        if existing.status != "pending" {
            return error(string `Leave request "${requestId}" is ${existing.status}, not pending, so it cannot be approved`);
        }
        LeaveRequest updated = existing.clone();
        updated.status = "approved";
        updated.managerNote = note;
        leaveRequests[requestId] = updated;
        return updated.clone();
    }
}

# Rejects a pending leave request. Refunds any annual leave balance that
# was deducted when the request was filed (unpaid leave never deducts one).
#
# + requestId - The request's id, as returned by requestLeave or listMyLeaveRequests
# + reason - Why the request is being turned down
# + return - The updated request, or an error if no request has that id or it is not pending
@ai:AgentTool
isolated function rejectLeaveRequest(string requestId, string reason) returns LeaveRequest|error {
    LeaveRequest existing;
    lock {
        LeaveRequest? found = leaveRequests[requestId];
        if found is () {
            return error(string `No leave request found with id "${requestId}"`);
        }
        if found.status != "pending" {
            return error(string `Leave request "${requestId}" is ${found.status}, not pending, so it cannot be rejected`);
        }
        existing = found.clone();
    }

    if existing.leaveType == "annual" {
        lock {
            Employee? employee = employees[existing.employeeId];
            if employee is Employee {
                Employee refunded = employee.clone();
                refunded.annualLeaveBalance += existing.numberOfDays;
                employees[existing.employeeId] = refunded;
            }
        }
    }

    LeaveRequest updated = existing.clone();
    updated.status = "rejected";
    updated.managerNote = reason;
    lock {
        leaveRequests[requestId] = updated.clone();
    }
    return updated;
}

# Returns today's date, so the agent can resolve relative dates
# before calling a tool that needs one.
#
# + return - Today's date
@ai:AgentTool
isolated function getCurrentDate() returns time:Date {
    time:Civil {year, month, day} = time:utcToCivil(time:utcNow());
    return {year, month, day};
}

final ai:Agent leaveAssistantAgent = check new ({
    systemPrompt: {
        role: "Leave Assistant",
        instructions: string `You are an HR assistant that handles employee leave requests.
            Always get the employee's id before checking a balance, filing a
            request, or listing requests, since every action is scoped to one
            employee. Annual leave of ${AUTO_APPROVE_MAX_DAYS} days or fewer,
            and all sick leave, are approved automatically as long as there is
            enough balance. Longer annual leave and every unpaid request stay
            pending until approveLeaveRequest or rejectLeaveRequest is called.
            Resolve relative dates, such as tomorrow or next Monday, against
            the current date before filing a request, and refer back to a
            request by the id returned from requestLeave or
            listMyLeaveRequests when cancelling, approving, or rejecting it.`
    },
    tools: [getLeaveBalance, requestLeave, listMyLeaveRequests, cancelLeaveRequest,
            approveLeaveRequest, rejectLeaveRequest, getCurrentDate],
    model: check new openai:ModelProvider(openAiApiKey, openai:GPT_4O)
});
