import ballerina/ai;
import ballerina/http;
import ballerina/time;
import ballerina/uuid;
import ballerinax/ai.openai;
import ballerinax/amp as _;

// Provide the OpenAI API key via Config.toml (configurable).
configurable string openAiApiKey = ?;

// Root-mounted so the agent exposes exactly `POST /chat` on port 8000 —
// the fixed contract Agent Manager's "Chat Agent" interface type expects.
service / on new ai:Listener(8000) {
    resource function post chat(@http:Payload ai:ChatReqMessage request)
                        returns ai:ChatRespMessage|error {
        string response = check taskAssistantAgent.run(request.message, request.sessionId);
        return {message: response};
    }
}

# A single to-do item.
#
# + id - Unique identifier, generated by `addTask`
# + description - What the task involves
# + dueBy - When the task is due, if set
# + createdAt - When the task was created
# + completedAt - When the task was marked complete, if it has been
# + completed - Whether the task is done
type Task record {|
    string id;
    string description;
    time:Date dueBy?;
    time:Date createdAt = time:utcToCivil(time:utcNow());
    time:Date completedAt?;
    boolean completed = false;
|};

// Simple in-memory task store, keyed by task id.
isolated map<Task> tasks = {
    "a2af0faa-3b73-4184-9be1-87b29a963be6": {
        id: "a2af0faa-3b73-4184-9be1-87b29a963be6",
        description: "Buy groceries",
        dueBy: time:utcToCivil(time:utcAddSeconds(time:utcNow(), 60 * 5))
    }
};

# Adds a new task to the to-do list.
#
# + description - What the task involves
# + dueBy - When the task is due, if known
# + return - The newly created task (including its id, for later reference), or an error
@ai:AgentTool
isolated function addTask(string description, time:Date? dueBy) returns Task|error {
    string id = uuid:createRandomUuid();
    Task newTask = {id, description, dueBy: dueBy.clone()};
    lock {
        tasks[id] = newTask.clone();
    }
    return newTask;
}

# Lists every task, both pending and completed.
#
# + return - All tasks currently on the list
@ai:AgentTool
isolated function listTasks() returns Task[] {
    lock {
        return tasks.toArray().clone();
    }
}

# Marks a task as completed.
#
# + id - The id of the task to complete, as returned by `addTask` or `listTasks`
# + return - The updated task, or an error if no task has that id
@ai:AgentTool
isolated function completeTask(string id) returns Task|error {
    lock {
        Task? existing = tasks[id];
        if existing is () {
            return error(string `No task found with id "${id}"`);
        }
        Task updated = existing.clone();
        updated.completed = true;
        updated.completedAt = time:utcToCivil(time:utcNow());
        tasks[id] = updated;
        return updated.clone();
    }
}

# Changes a task's due date, use this when the user wants to reschedule
# something rather than create a new task.
#
# + id - The id of the task to reschedule, as returned by `addTask` or `listTasks`
# + dueBy - The new due date
# + return - The updated task, or an error if no task has that id
@ai:AgentTool
isolated function rescheduleTask(string id, time:Date dueBy) returns Task|error {
    lock {
        Task? existing = tasks[id];
        if existing is () {
            return error(string `No task found with id "${id}"`);
        }
        Task updated = existing.clone();
        updated.dueBy = dueBy.clone();
        tasks[id] = updated;
        return updated.clone();
    }
}

# Permanently removes a task from the list.
#
# + id - The id of the task to delete, as returned by `addTask` or `listTasks`
# + return - An error if no task has that id
@ai:AgentTool
isolated function deleteTask(string id) returns error? {
    lock {
        if !tasks.hasKey(id) {
            return error(string `No task found with id "${id}"`);
        }
        Task _ = tasks.remove(id);
    }
}

# Returns today's date, so the agent can resolve relative dates
# before calling a tool that needs one.
#
# + return - Today's date
@ai:AgentTool
isolated function getCurrentDate() returns time:Date {
    time:Civil {year, month, day} = time:utcToCivil(time:utcNow());
    return {year, month, day};
}

// Define an AI agent with a system prompt and a set of tools.
// The agent will use these tools to help manage a task list,
// following the system prompt instructions.
final ai:Agent taskAssistantAgent = check new ({
    systemPrompt: {
        role: "Task Assistant",
        instructions: string `You are a helpful assistant for managing a to-do list.
            You can add, list, complete, reschedule, and delete tasks, and help
            the user plan their day. Resolve relative dates, such as tomorrow
            or next Friday, against the current date before calling a tool
            that needs one, and refer back to a task by the id returned from
            addTask or listTasks when completing, rescheduling, or deleting it.`
    },
    // Specify the functions the agent can use as tools.
    tools: [addTask, listTasks, completeTask, rescheduleTask, deleteTask, getCurrentDate],
    // Use OpenAI as the model provider.
    model: check new openai:ModelProvider(openAiApiKey, openai:GPT_4O)
});
